# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/bd/link/ip/link_Ifetc32_0_0/link_Ifetc32_0_0.xci
# IP: The module: 'link_Ifetc32_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/bd/link/ip/link_Ifetc32_0_0/link_Ifetc32_0_0.xci
# IP: The module: 'link_Ifetc32_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/prgrom/prgrom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
