# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/project_uart_update/project_uart_update.srcs/sources_1/ip/program_rom/program_rom.xci
# IP: The module: 'program_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/project_uart_update/project_uart_update.srcs/sources_1/ip/program_rom/program_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/project_uart_update/project_uart_update.srcs/sources_1/ip/program_rom/program_rom.xci
# IP: The module: 'program_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/project_uart_update/project_uart_update.srcs/sources_1/ip/program_rom/program_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
