# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/bd/link/ip/link_dmemory32_0_1/link_dmemory32_0_1.xci
# IP: The module: 'link_dmemory32_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM_ooc.xdc

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/bd/link/ip/link_dmemory32_0_1/link_dmemory32_0_1.xci
# IP: The module: 'link_dmemory32_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM_ooc.xdc
