# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Spring 2021/orgnization/proj/SUSTech-CS202-ComputerOrganization-Project/top_test/top/top.srcs/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
